# Generated by Django 5.1.4 on 2025-02-08 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_tags', models.BooleanField(default=True, help_text='Can this author create tags?')),
                ('can_add_books', models.BooleanField(default=True, help_text='Can this author add new books to the library?')),
                ('bio', models.TextField(blank=True, help_text='Short biography of the author.', null=True)),
                ('website', models.URLField(blank=True, help_text="Author's personal website.", null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
